#include "ascii.h"

#define ASCII_WANT_DEC
#include "ascii_defs.inc"

DEFINE_FROM_ASCII_DEC(uint8)
DEFINE_FROM_ASCII_DEC(uint16)
DEFINE_FROM_ASCII_DEC(uint32)

DEFINE_FROM_ASCII_HEX(uint8)
DEFINE_FROM_ASCII_HEX(uint16)
DEFINE_FROM_ASCII_HEX(uint32)

DEFINE_TO_ASCII_HEX(uint8)
DEFINE_TO_ASCII_HEX(uint16)
DEFINE_TO_ASCII_HEX(uint32)
