add wave sim:/EchoTestbench/CPU/CPUGlobal -color grey sim:/EchoTestbench/xCPUx/CPUGlobal
add wave sim:/EchoTestbench/CPU/DMEM -color grey sim:/EchoTestbench/xCPUx/DMEM
add wave sim:/EchoTestbench/CPU/IMEM -color grey sim:/EchoTestbench/xCPUx/IMEM
add wave sim:/EchoTestbench/CPU/IOMAP -color grey sim:/EchoTestbench/xCPUx/IOMAP
add wave sim:/EchoTestbench/CPU/IMEM_addrb -color grey sim:/EchoTestbench/xCPUx/IMEM_addrb
add wave sim:/EchoTestbench/CPU/IMEM_doutb -color grey sim:/EchoTestbench/xCPUx/IMEM_doutb
add wave sim:/EchoTestbench/CPU/REGFILE_ra1 -color grey sim:/EchoTestbench/xCPUx/REGFILE_ra1
add wave sim:/EchoTestbench/CPU/REGFILE_ra2 -color grey sim:/EchoTestbench/xCPUx/REGFILE_ra2
add wave sim:/EchoTestbench/CPU/REGFILE_wa -color grey sim:/EchoTestbench/xCPUx/REGFILE_wa
add wave sim:/EchoTestbench/CPU/REGFILE_rd1 -color grey sim:/EchoTestbench/xCPUx/REGFILE_rd1
add wave sim:/EchoTestbench/CPU/REGFILE_rd2 -color grey sim:/EchoTestbench/xCPUx/REGFILE_rd2
add wave sim:/EchoTestbench/CPU/REGFILE_wd -color grey sim:/EchoTestbench/xCPUx/REGFILE_wd
add wave sim:/EchoTestbench/CPU/REGFILE_we -color grey sim:/EchoTestbench/xCPUx/REGFILE_we
add wave sim:/EchoTestbench/CPU/DOBranch_DX_WF_ -color grey sim:/EchoTestbench/xCPUx/DOBranch_DX_WF_
add wave sim:/EchoTestbench/CPU/PCBranch_DX_WF_ -color grey sim:/EchoTestbench/xCPUx/PCBranch_DX_WF_
add wave sim:/EchoTestbench/CPU/WBKReg_M_WF_ -color grey sim:/EchoTestbench/xCPUx/WBKReg_M_WF_
add wave sim:/EchoTestbench/CPU/WBKDat_M_WF_ -color grey sim:/EchoTestbench/xCPUx/WBKDat_M_WF_
add wave sim:/EchoTestbench/CPU/WBKCanFWD_M_WF_ -color grey sim:/EchoTestbench/xCPUx/WBKCanFWD_M_WF_
add wave sim:/EchoTestbench/CPU/PC_WF_ -color grey sim:/EchoTestbench/xCPUx/PC_WF_
add wave sim:/EchoTestbench/CPU/INST_WF_ -color grey sim:/EchoTestbench/xCPUx/INST_WF_
add wave sim:/EchoTestbench/CPU/StepCount -color grey sim:/EchoTestbench/xCPUx/StepCount
add wave sim:/EchoTestbench/CPU/StallCount -color grey sim:/EchoTestbench/xCPUx/StallCount
add wave sim:/EchoTestbench/CPU/PC_DX -color grey sim:/EchoTestbench/xCPUx/PC_DX
add wave sim:/EchoTestbench/CPU/INST_DX -color grey sim:/EchoTestbench/xCPUx/INST_DX
add wave sim:/EchoTestbench/CPU/FWD_Allow -color grey sim:/EchoTestbench/xCPUx/FWD_Allow
add wave sim:/EchoTestbench/CPU/FWD_1 -color grey sim:/EchoTestbench/xCPUx/FWD_1
add wave sim:/EchoTestbench/CPU/FWD_2 -color grey sim:/EchoTestbench/xCPUx/FWD_2
add wave sim:/EchoTestbench/CPU/FWD_rd1 -color grey sim:/EchoTestbench/xCPUx/FWD_rd1
add wave sim:/EchoTestbench/CPU/FWD_rd2 -color grey sim:/EchoTestbench/xCPUx/FWD_rd2
add wave sim:/EchoTestbench/CPU/IControlDX_ -color grey sim:/EchoTestbench/xCPUx/IControlDX_
add wave sim:/EchoTestbench/CPU/MemAddrDX_ -color grey sim:/EchoTestbench/xCPUx/MemAddrDX_
add wave sim:/EchoTestbench/CPU/MemWValueDX_ -color grey sim:/EchoTestbench/xCPUx/MemWValueDX_
add wave sim:/EchoTestbench/CPU/RegWValueDX_ -color grey sim:/EchoTestbench/xCPUx/RegWValueDX_
add wave sim:/EchoTestbench/CPU/PCPLUS8DX_ -color grey sim:/EchoTestbench/xCPUx/PCPLUS8DX_
add wave sim:/EchoTestbench/CPU/IControl_M -color grey sim:/EchoTestbench/xCPUx/IControl_M
add wave sim:/EchoTestbench/CPU/IControl__M -color grey sim:/EchoTestbench/xCPUx/IControl__M
add wave sim:/EchoTestbench/CPU/MemAddr__M -color grey sim:/EchoTestbench/xCPUx/MemAddr__M
add wave sim:/EchoTestbench/CPU/MemAddr_M -color grey sim:/EchoTestbench/xCPUx/MemAddr_M
add wave sim:/EchoTestbench/CPU/MemWValue__M -color grey sim:/EchoTestbench/xCPUx/MemWValue__M
add wave sim:/EchoTestbench/CPU/RegWValue_M -color grey sim:/EchoTestbench/xCPUx/RegWValue_M
add wave sim:/EchoTestbench/CPU/PCPLUS8_M -color grey sim:/EchoTestbench/xCPUx/PCPLUS8_M
add wave sim:/EchoTestbench/CPU/DBG_cycle -color grey sim:/EchoTestbench/xCPUx/DBG_cycle
add wave sim:/EchoTestbench/CPU/DBG_step -color grey sim:/EchoTestbench/xCPUx/DBG_step

