TARGET := bench
LDSTYLE := inject_cache
FIXED_ELF ?= ../gios/gios.elf
#SSRCS := start.s

include ../makefile.pre

#CSRCS += ../common/graphics.c ../common/benchmark.c ../common/uart.c ../common/ascii.c
#NOPTOBJS += ../common/mutmath.nopt.c

include ../makefile.in
