
$(TARGET).elf: $(ELF_INPUT)
	$(PGCC) $(ELF_CCOPT) $^ $(LIBOPTS) -T $(LDSRC) -o $@
	$(PSIZE) $@
#	$(PSTRIP) -R .pdr -R .comment -R .reginfo $@
#	$(PSIZE) $@
	chmod -x $@

#C sources with .nopt.c get "NOPOPT"
%.nopt.c.o: %.nopt.c
	$(PGCC) $(CCMIPS) $(CCOPTS) $(NOPOPT) -o $@ -c $<
%.nopt.c.ll: %.nopt.c
	$(PCLANG) $(CCOPTS) $(NOPOPT) -emit-llvm -o $@ -x c $<
%.nopt.c.ll.o: %.nopt.c.ll
	$(PLLC) -o $@ $<
%.nopt.c.ll.s: %.c
	$(PCLANG) $(CCMIPS) $(CCOPTS) $(NOPOPT) -S -o $@ -x c $<
#...others get "OPTOPT"
%.c.o: %.c
	$(PGCC) $(CCMIPS) $(CCOPTS) $(OPTOPT) -o $@ -c $<
%.c.ll: %.c
	$(PCLANG) $(CCOPTS) $(OPTOPT) -emit-llvm -o $@ -x c $<
%.c.ll.s: %.c
	$(PCLANG) $(CCMIPS) $(CCOPTS) $(OPTOPT) -S -o $@ -x c $<
%.s.o: %.s
	$(PGAS) $(ASOPTS) -o $@ $<


%.bin: %.elf
	-$(PCOPY) -j .text -p -O binary $< $@
	-chmod -x $@
%.inst.bin: %.elf
	-$(PCOPY) -j .text -p -O binary $^ $@
	-chmod -x $@
%.data.bin: %.elf
	-$(PCOPY) -j .data -p -O binary $^ $@
	-chmod -x $@
#%.both.bin: %.elf
#	-$(PCOPY) -j .both -p -O binary $^ $@
#	-chmod -x $@
#%.both.bin: %.data.bin %.inst.bin
#	truncate -s 16K $@
#	cat $^ > $@
#%.both.mem: %.data.bin %.inst.bin
#	bin2mem     0 < $*.data.bin > $@
#	bin2mem 16384 < $*.inst.bin | sed s/^@00000000/@00004000/ >> $@


%.dump: %.elf
	-$(PDUMP) $^ -xsD >$@
%.inst.dump: %.elf
	-$(PDUMP) -j .text $^ -xsSDl >$@
%.data.dump: %.elf
	-($(PDUMP) -j .data $^ -xS >$@ || exit 0)

%.inst.hex: %.elf
	-$(PCOPY) -j .text -O verilog $^ $@
%.data.hex: %.elf
	-$(PCOPY) -j .data -O verilog $^ $@


%.mif: %.bin
	bin2mif < $^ > $@
%.coe: %.bin
	bin2coe < $^ > $@
%.mem: %.bin
	bin2mem 0 < $^ > $@
%.v: %.bin
	bin2rom < $^ > $@


clean:
	$(RM) -f *.o *.ll *.ll.s *.c.s *.elf *.bin *.mif *.coe *.mem *.v *.hex *.dump *.log $(OBJS)

.PHONY: clean $(TARGET) elf dump data inst both bins
.PRECIOUS: %.s %.c.ll %.c.ll.s
.SECONDARY:
