LDSTYLE ?= inject_basic
LDSRC ?= ../link/$(LDSTYLE).ld
START ?= ../link/$(LDSTYLE).s

ALLCS ?= $(wildcard *.c)
NOPTS ?= $(wildcard *.nopt.c)
CSRCS ?= $(filter-out $(NOPTS),$(ALLCS))
SSRCS ?= $(wildcard *.s) $(START)

OUTS ?= mif coe mem hex # "dump v"
SECS ?= inst data

OBJS = $(SOBJS) $(COBJS)
SOBJS = $(SSRCS:%.s=%.s.o)
#COBJS = $(CSRCS:%.c=%.c.ll.s.o)
#COBJS = $(CSRCS:%.c=%.c.ll.o)
COBJS = $(CSRCS:%.c=%.c.o)
NOPTOBJS = $(NOPTS:%.c=%.c.o)

default: all
elf: $(TARGET).elf
dump: $(TARGET).dump $(TARGET).inst.dump $(TARGET).data.dump
data: $(OUTS:%=$(TARGET).data.%)
inst: $(OUTS:%=$(TARGET).inst.%)
bins: $(SECS:%=$(TARGET).%.bin)


RM ?= `which "/bin/rm" 2>/dev/null || echo "rm"`
CLANG  ?= clang
LLC    ?= llc

M_ARCH ?= mips
M_TRI  ?= $(M_ARCH)-unknown-elf #The compiler is actually mips-linux-gnu
M_DIR  ?=
#M_PRE  ?= $(M_DIR)$(M_ARCH)-
M_PRE  ?= mips-linux-gnu-

PGCC   ?= $(M_PRE)gcc
PGAS   ?= $(M_PRE)as
PSTRIP ?= $(M_PRE)strip
PSIZE  ?= $(M_PRE)size
PDUMP  ?= $(M_PRE)objdump
PCOPY  ?= $(M_PRE)objcopy

ASOPTS ?= -mips1 -march=mips1 -mabi=32 --no-break --no-trap  -mno-pdr -non_shared -mno-shared -R -g2
# -O0
CCOPTS ?= -pipe -fasm -std=gnu99 -ffreestanding -g
OPTOPT ?= -Os
NOPOPT ?= -O0
CCMIPS ?= -mips1 -march=mips1 -mabi=32 -mno-abicalls -msoft-float -mno-dsp -mno-mips3d -mlong32 -mno-branch-likely -mno-flush-func -fno-PIE -fno-PIC -fno-pie -fno-pic -fno-exceptions -Wa,-mno-pdr,-non_shared,-mno-shared,-O,-R
# -G0
# -Wl,--strip-debug


# -pedantic
PCLANG ?= $(CLANG) -cc1 -triple=$(M_TRI) -target-cpu mips1 -target-abi o32 -mrelocation-model static
LIBOPTS ?= -nostartfiles -nostdlib -nodefaultlibs -static
PLLC   ?= $(LLC) -march=$(M_ARCH) -relocation-model=static

