#!/bin/bash

if [ -e "m.pid" ]; then
  echo "ALREADY RUNNING:"
  cat m.pid
  exit 1
fi

rm -Rf m.pid #Shouldn't exist
touch m.pid #Temporary (don't know pid yet)

#Start fresh logs (out & err)
echo -e "MAKE '$0': $@" |tee m.out m.err
date |tee -a m.out m.err
echo -e "\n\n" |tee m.out m.err

#Run the make itself (as sub-process)
make $@ > >(tee -a m.out | grep -n -f sparse.grep) 2> >(tee -a m.err >&2) &
PID="$!"

echo "PID: $PID" |tee m.pid #Flag as running (real PID now)

wait $pid
echo -e "\n\n*** DONE ($PID) ***\n" |tee -a m.out m.err
rm m.pid

exit 0
