#!/bin/bash -eux

HDIV="\n\n_________________________/^\\____________________________\n/n"

reset
make lint
echo "${HDIV}"

make synth
echo "${HDIV}"

make impl
echo "${HDIV}"

make warn
echo "${HDIV}"

