TARGET := check3
LDSTYLE := inject_cache
#SSRCS := start.s
#LIBOPTS ?= -nostartfiles -nodefaultlibs
LIBOPTS ?= -nostartfiles

#include ../Makefile.llvm.in
#include ../Makefile.gcc.in
include ../Makefile.in
