
SUBS ?= $(shell find * -mindepth 1 -maxdepth 1 -name "Makefile" -printf '%h ')

.PHONY: all clean $(SUBS)

all clean: $(SUBS)
	@echo "DONE: $@ ($^)"

$(SUBS):
	@echo ""
	$(MAKE) --no-builtin-rules -C $@ $(MAKECMDGOALS)
	@echo ""
