//#include <stdint.h>
#include <stdio.h>
#include <math.h>
#include <stdbool.h>
//#include <float.h>


double normalizeRadians(double angle) {
    while (angle < 0) {
        angle += 2 * M_PI;
    }
    while (angle >= 2 * M_PI) {
        angle -= 2 * M_PI;
    }
    return angle;
}

void printCoordinate(const int hand, double angle, const double radius, bool last) {
    const double angleNorm = normalizeRadians(angle);
    const int x = round(cos(angleNorm) * radius);
    const int y = round(sin(angleNorm) * radius);
    const char lastChar = last ? ' ' : ',';

    printf("    {%4d,%4d}%c  // %2d  RAD=%02.5f  DEG=%04.2f\n", x, y, lastChar, hand, angleNorm, angle * 180 / M_PI);
}

int main() {
    const double radius = 20.0; // Arbitrary but a reasonable size for later scaling
    const double zeroAngle = M_PI / 2; // 90 degrees as radians: Top of the clock face
    const double step = -2 * M_PI / 60; // radians: clockwise 60 sec/min per diameter
    const int LAST_HAND = 59; // Last hand position (0-59)

    printf("// This file is auto-generated by tool/clocker.c\n");
    printf("//     Table of offset coordinates for 60 clock hand positions around a clock face.\n");
    printf("struct clockHand {\n");
    printf("    signed char x;\n");
    printf("    signed char y;\n");
    printf("};\n");
    printf("static struct clockHand clockTable[60] = {\n");
    printf("    // (RADIUS=%f START=%f STEP=%f)\n", radius, zeroAngle, step);
    for (int hand = 0; hand <= LAST_HAND; hand++) {
        printCoordinate(hand, zeroAngle+(step*hand), radius, hand==LAST_HAND);
    }
    printf("};\n");

    return 0;
}
