BINFILES ?= $(wildcard *.bin)
TARGETS ?= $(BINFILES:%.bin=%)
MIFS ?= $(TARGETS:%=%.mif)
COES ?= $(TARGETS:%=%.coe)
VEES ?= $(TARGETS:%=%.v)
ASMS ?= $(TARGETS:%=%.s)
MEMS ?= $(TARGETS:%=%.mem)


default: all

all: count mifs coes vees asms mems

count: $(BINFILES)
	ls -al $(BINFILES)
	wc -c $(BINFILES)

mifs: $(MIFS)

coes: $(COES)

vees: $(VEES)

asms: $(ASMS)

mems: $(MEMS)

%.mif: %.bin
	bin2mif < $< > $@

%.coe: %.bin
	bin2coe < $< > $@

%.mem: %.bin
	bin2mem < $< > $@

%.v: %.bin
	bin2rom test 0 < $< > $@

%.s: %.bin
	bin2hack test 0 < $< > $@

clean:
	rm -f rm *.bin *.coe *.mif *.mem *.v

.phony: clean all count mifs coes mems vees asms

